# -*- coding: utf-8 -*-
"""Cafe_Sales_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kUajSHncxdDZHs7_ZVu1urqJPyqD33r
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('dirty_cafe_sales.csv')
df

#eliminiamo le colonne inutili
df=df.drop(columns=['Transaction ID'])
df

#rendiamo item una stringa
df['Item']=df['Item'].astype('string')
df.info()
#rendiamo le colonne numeriche depositarie di
#dati numerici
cols=['Quantity','Price Per Unit','Total Spent']
df[cols]=df[cols].apply(pd.to_numeric, errors='coerce')
df.info()
#i valori nulli non sono aumentati, sono solo piu
#visibili: error ora è un valore nullo!

cols=['Payment Method', 'Location', 'Transaction Date']
df[cols]=df[cols].astype('string')
df.info()
#per puro esercizio abbiamo cambiato tipo
#ad ogni variabile!

#eliminiamo duplicati
df.drop_duplicates(keep="first", inplace=True)
df.duplicated().sum()

df['Location'].isnull().sum()
#'Location' manca di 1/3 dei dati, conviene sostituire i valori mancanti con 'Unknown'
df['Location'] = df['Location'].fillna('unknown')
df['Location'] = df['Location'].replace('ERROR', 'unknown')
df['Location'] = df['Location'].str.lower()
df['Location'].unique()
df['Location'].value_counts()
df['Location'].isnull().sum()
#abbiamo risolto il problema dei NaN della colonna 'Location'

df.shape

df.info()

#adesso bisogna occuparsi del payment method...
df['Payment Method'].unique()
df['Payment Method'].value_counts()

df['Payment Method'] = df['Payment Method'].fillna('unknown')
df['Payment Method'] = df['Payment Method'].replace('ERROR', 'unknown')
df['Payment Method'] = df['Payment Method'].replace('error', 'unknown')
df['Payment Method'] = df['Payment Method'].str.lower()
df['Payment Method'].isnull().sum()

df.isnull().sum()

df['Item'] = df['Item'].dropna()
df['Item'].value_counts()
df['Item'].groupby(df['Price Per Unit']).value_counts()

#possiamo rilevare come manchino dati riguardo alcuni oggetti venduti, ma possiamo
#risalire al dato grazie alla correlazione con il loro prezzo
#purtroppo su alcuni dati ci sono più valori di coincidenza e quindi dovremmo rinunciarci

df['Item'] = df['Item'].str.lower()
df['Item'] = np.where(
    (df['Item'].isin(['unknown', 'error'])) & (df['Price Per Unit'] == 1), 'cookie', df['Item'])
df['Item'] = np.where(
    (df['Item'].isin(['unknown', 'error'])) & (df['Price Per Unit'] == 1.5), 'tea', df['Item'])

df['Item'] = np.where(
    (df['Item'].isin(['unknown', 'error'])) & (df['Price Per Unit'] == 2), 'coffee', df['Item'])
df['Item'] = np.where(
    (df['Item'].isin(['unknown', 'error'])) & (df['Price Per Unit'] == 5), 'salad', df['Item'])
df = df[~df['Item'].isin(['unknown', 'error'])]
df['Item'].fillna('unknown', inplace=True)
df['Item'].value_counts().plot(kind='barh')

#eliminando valori 'unfillable' avremo un df di 9357 dati

df.info()

#adesso bisogna occuparci di Quantity, Price Per Unit e Total spent

(df['Quantity']== 0).sum()
#non ci sono valori di 'Quantity' == 0, quindi possiamo cercare valori mancanti
#in base all'equazione: Total Spent = Quantity * Price Per Unit

df.loc[
    df['Quantity'].isna() & df['Price Per Unit'].notna() & df['Total Spent'].notna(),
    'Quantity'

] = df['Total Spent'] / df['Price Per Unit']
df['Quantity'].isnull().sum()

#in questo caso tramite la formula abbiamo trovato circa 400 dati ignoti

df.dropna(subset=['Quantity'], inplace=True)
df.info()

#Cerchiamo di recuperare info anche dalle colonne Price Per Unit e Total Spent

df.loc[
    df['Price Per Unit'].isna() & df['Quantity'].notna() & df['Total Spent'].notna(),
    'Price Per Unit'
] = df['Total Spent'] / df['Quantity']
df['Price Per Unit'].isnull().sum()

#anche in questo caso evitando di usare drop.na riusciamo a salvare
#oltre 400 informazioni

df.dropna(subset=['Price Per Unit'], inplace=True)
df['Price Per Unit'].isnull().sum()

#siamo riusciti a pulire quasi tutte le colonne numeriche tramite questa
#formula, adesso manca l'ultima operazione

df.loc[
    df['Total Spent'].isna() & df['Quantity'].notna() & df['Price Per Unit'].notna(),
    'Total Spent'
] = df['Quantity'] * df['Price Per Unit']
df['Total Spent'].isna().sum()

#riflettendoci essendo rimasta come ultima incognita, avremmo potuto
#semplicemente indicare l'operazione da fare, come?
#df['Total Spent] = df['Quantity] * df['Price Per Unit]
#...
#in ogni caso abbiamo quasi completato la pulizia del df

df['Item'] = df['Item'].astype('string')
df.info()

#Sostituiamo i NaN di Transaction Date con 'unknown'
df['Transaction Date'].fillna('unknown', inplace=True)
df['Transaction Date'].isna().sum()

df.info()

#adesso abbiamo un df senza NaN su cui operare!

df.reset_index(inplace=True)

#reset dell'indice per avere un df ordinato

df[df['Item'] != 'unknown'].groupby('Item')['Total Spent'].mean().plot(kind='barh', color='skyblue', figsize=(10,5))

#da notare come rimuoviamo 300 unknown su 9500

plt.xlabel('Average Total Spent')
plt.ylabel('Item')
plt.title('Average Total Spent per Item')
plt.show()

#'salad' è l'item più costoso tra i selezionabili e di fatto permette incassi
#tendenzialmente superiori su singole transazioni
#se conoscessimo il costo dei singoli item potremmo facilmente stabilirne il
#profitto a breve e lungo termine
#ma questo è solo un esempio di analisi dati.

df.to_csv('cleaned_data.csv')

